[tools]
go = "1.25.5"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"github:golangci/golangci-lint" = "2.7.2"
"github:goreleaser/goreleaser" = "v2.13.1"
"github:anchore/quill" = "v0.5.1"
"github:jstemmer/go-junit-report" = "v2.1.0"
