[tools]
go = "1.25.7"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"github:golangci/golangci-lint" = "2.10.1"    # renovate: datasource=github-releases depName=golangci/golangci-lint
"github:goreleaser/goreleaser" = "v2.13.3"   # renovate: datasource=github-releases depName=goreleaser/goreleaser
"github:anchore/quill" = "v0.5.1"            # renovate: datasource=github-releases depName=anchore/quill
"github:jstemmer/go-junit-report" = "v2.1.0" # renovate: datasource=github-releases depName=jstemmer/go-junit-report
