[tools]
go = "1.25.4"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"ubi:golangci/golangci-lint" = "2.6.1"
"ubi:goreleaser/goreleaser" = "v2.9.0"
"ubi:anchore/quill" = "v0.5.1"
"ubi:jstemmer/go-junit-report" = "v2.1.0"

[settings]
# Experimental features are needed for the Go backend
experimental = true
